from tkinter import *
raiz = Tk()

raiz.title("Parqués")

miFrame = Frame(raiz)
miFrame.pack()


#------------Pantalla--------------
pantalla = Entry(miFrame, width=10)
pantalla.grid(row=0, column=10, pady=10, columnspan=4, sticky="WENS")
botonDado1 = Button(miFrame, text="dado1", width=3)
botonDado1.grid(row=0, column=9, padx=5, pady=10, sticky="WENS")
botonDado2 = Button(miFrame, text="dado2", width=3)
botonDado2.grid(row=0, column=8, padx=5, pady=10, sticky="WENS")

botonSoplar = Button(miFrame, text="Envigado", width=10)
botonSoplar.grid(row=4, column=20, sticky="WENS")

botonSuma = Button(miFrame, text="Suma", width=10)
botonSuma.grid(row=2, column=20, sticky="WENS")

FichaRoja1 = PhotoImage(file= 'D:\LEONARDO ARAQUE\Downloads\pngwing.com.png')

#------------ BASES --------------
baseRoja = Button(miFrame, text="BASE ROJA", bg="#e32314", fg="White")
baseRoja.grid(row=1, column=0, columnspan=8, rowspan=8, sticky="WENS")

baseAmarilla = Button(miFrame, text="BASE AMARILLA", bg="#F7DE3A", fg="White")
baseAmarilla.grid(row=12, column=0, columnspan=8, rowspan=8, sticky="WENS")

baseVerde = Button(miFrame, text="BASE VERDE", bg="green", fg="White")
baseVerde.grid(row=1, column=11, columnspan=8, rowspan=8, sticky="WENS")

baseAzul = Button(miFrame, text="BASE AZUL", bg="blue", fg="White")
baseAzul.grid(row=12, column=11, columnspan=8, rowspan=8, sticky="WENS")

#------------ META -----------------
bMeta = Button(miFrame, bg="#43B3AE",)
bMeta.grid(row=9, column=8,columnspan=3, rowspan=3, sticky="WENS")


#------------Tablero Superior--------------
b1 = Button(miFrame, width=10, bg="white")
b1.grid(row=1, column=8, sticky="WENS")
b2 = Button(miFrame, width=10, bg="white")
b2.grid(row=2, column=8, sticky="WENS")
b3 = Button(miFrame, width=10, bg="white")
b3.grid(row=3, column=8, sticky="WENS")
b4 = Button(miFrame, width=10, bg="white")
b4.grid(row=4, column=8, sticky="WENS")
bSalidaRoja = Button(miFrame, width=10, bg="#e32314")
bSalidaRoja.grid(row=5, column=8, sticky="WENS")
b6 = Button(miFrame, width=10, bg="white")
b6.grid(row=6, column=8, sticky="WENS")
b7 = Button(miFrame, width=10, bg="white")
b7.grid(row=7, column=8, sticky="WENS")
b8 = Button(miFrame, width=10, bg="white")
b8.grid(row=8, column=8, sticky="WENS")

b67 = Button(miFrame, width=10, bg="white")
b67.grid(row=1, column=10, sticky="WENS")
b66 = Button(miFrame, width=10, bg="white")
b66.grid(row=2, column=10, sticky="WENS")
b65 = Button(miFrame, width=10, bg="white")
b65.grid(row=3, column=10, sticky="WENS")
b64 = Button(miFrame, width=10, bg="white")
b64.grid(row=4, column=10, sticky="WENS")
bSeguro7 = Button(miFrame, width=10, text="★", bg="green", fg="white")
bSeguro7.grid(row=5, column=10, sticky="WENS")
b62 = Button(miFrame, width=10, bg="white")
b62.grid(row=6, column=10, sticky="WENS")
b61 = Button(miFrame, width=10, bg="white")
b61.grid(row=7, column=10, sticky="WENS")
b60 = Button(miFrame, width=10, bg="white")
b60.grid(row=8, column=10, sticky="WENS")

#----Escalera Roja-----
bSeguro8 = Button(miFrame, width=10, text="★", bg="#e32314", fg="White")
bSeguro8.grid(row=1, column=9, sticky="WENS")
bEscaRoja1 = Button(miFrame, width=10, bg="#e32314")
bEscaRoja1.grid(row=2, column=9, sticky="WENS")
bEscaRoja2 = Button(miFrame, width=10, bg="#e32314")
bEscaRoja2.grid(row=3, column=9, sticky="WENS")
bEscaRoja3 = Button(miFrame, width=10, bg="#e32314")
bEscaRoja3.grid(row=4, column=9, sticky="WENS")
bEscaRoja4 = Button(miFrame, width=10, bg="#e32314")
bEscaRoja4.grid(row=5, column=9, sticky="WENS")
bEscaRoja5 = Button(miFrame, width=10, bg="#e32314")
bEscaRoja5.grid(row=6, column=9, sticky="WENS")
bEscaRoja6 = Button(miFrame, width=10, bg="#e32314")
bEscaRoja6.grid(row=7, column=9, sticky="WENS")
bEscaRoja7 = Button(miFrame, width=10, bg="#e32314")
bEscaRoja7.grid(row=8, column=9, sticky="WENS")

#---------------Tablero Intermedio Izquierdo-------------------
b9 = Button(miFrame, width=2, height=4, bg="white")
b9.grid(row=9, column=7, sticky="NS")
b10 = Button(miFrame, width=2, height=4, bg="white")
b10.grid(row=9, column=6, sticky="NS")
b11 = Button(miFrame, width=2, height=4, bg="white")
b11.grid(row=9, column=5, sticky="NS")
bSeguro1 = Button(miFrame, width=2, height=4, text="★", bg="#e32314", fg="White")
bSeguro1.grid(row=9, column=4, sticky="NS")
b13 = Button(miFrame, width=2, height=4, bg="white")
b13.grid(row=9, column=3, sticky="NS")
b14 = Button(miFrame, width=2, height=4, bg="white")
b14.grid(row=9, column=2, sticky="NS")
b15 = Button(miFrame, width=2, height=4, bg="white")
b15.grid(row=9, column=1, sticky="NS")
b16 = Button(miFrame, width=2, height=4, bg="white")
b16.grid(row=9, column=0, sticky="NS")

b18 = Button(miFrame, width=2, height=4, bg="white")
b18.grid(row=11, column=0, sticky="NS")
b19 = Button(miFrame, width=2, height=4, bg="white")
b19.grid(row=11, column=1, sticky="NS")
b20 = Button(miFrame, width=2, height=4, bg="white")
b20.grid(row=11, column=2, sticky="NS")
b21 = Button(miFrame, width=2, height=4, bg="white")
b21.grid(row=11, column=3, sticky="NS")
bSalidaAmarilla = Button(miFrame, width=2, height=4, bg="#F7DE3A")
bSalidaAmarilla.grid(row=11, column=4, sticky="NS")
b23 = Button(miFrame, width=2, height=4, bg="white")
b23.grid(row=11, column=5, sticky="NS")
b24 = Button(miFrame, width=2, height=4, bg="white")
b24.grid(row=11, column=6, sticky="NS")
b25 = Button(miFrame, width=2, height=4, bg="white")
b25.grid(row=11, column=7, sticky="NS")

#----Escalera Anarilla-----
bSeguro2 = Button(miFrame, width=2, height=4, text="★", bg="#F7DE3A", fg="White")
bSeguro2.grid(row=10, column=0, sticky="NS")
bEscaAma1 = Button(miFrame, width=2, height=4, bg="#F7DE3A")
bEscaAma1.grid(row=10, column=1, sticky="NS")
bEscaAma2 = Button(miFrame, width=2, height=4, bg="#F7DE3A")
bEscaAma2.grid(row=10, column=2, sticky="NS")
bEscaAma3 = Button(miFrame, width=2, height=4, bg="#F7DE3A")
bEscaAma3.grid(row=10, column=3, sticky="NS")
bEscaAma4 = Button(miFrame, width=2, height=4, bg="#F7DE3A")
bEscaAma4.grid(row=10, column=4, sticky="NS")
bEscaAma5 = Button(miFrame, width=2, height=4, bg="#F7DE3A")
bEscaAma5.grid(row=10, column=5, sticky="NS")
bEscaAma6 = Button(miFrame, width=2, height=4, bg="#F7DE3A")
bEscaAma6.grid(row=10, column=6, sticky="NS")
bEscaAma7 = Button(miFrame, width=2, height=4, bg="#F7DE3A")
bEscaAma7.grid(row=10, column=7, sticky="NS")
#bMetaAmarilla = Button(miFrame, width=2, height=4, bg="#CCCCFF",)
#bMetaAmarilla.grid(row=10, column=8, sticky="NS")

#------------Tablero Intermedio Derecho--------------
b59 = Button(miFrame, width=3, height=4, bg="white")
b59.grid(row=9, column=11, sticky="NS")
b58 = Button(miFrame, width=2, height=4, bg="white")
b58.grid(row=9, column=12, sticky="NS")
b57 = Button(miFrame, width=2, height=4, bg="white")
b57.grid(row=9, column=13, sticky="NS")
bSalidaVerde = Button(miFrame, width=2, height=4, bg="green")
bSalidaVerde.grid(row=9, column=14, sticky="NS")
b55 = Button(miFrame, width=2, height=4, bg="white")
b55.grid(row=9, column=15, sticky="NS")
b54 = Button(miFrame, width=2, height=4, bg="white")
b54.grid(row=9, column=16, sticky="NS")
b53 = Button(miFrame, width=2, height=4, bg="white")
b53.grid(row=9, column=17, sticky="NS")
b52 = Button(miFrame, width=2, height=4, bg="white")
b52.grid(row=9, column=18, sticky="NS")

b50 = Button(miFrame, width=2, height=4, bg="white")
b50.grid(row=11, column=18, sticky="NS")
b49 = Button(miFrame, width=2, height=4, bg="white")
b49.grid(row=11, column=17, sticky="NS")
b48 = Button(miFrame, width=2, height=4, bg="white")
b48.grid(row=11, column=16, sticky="NS")
b47 = Button(miFrame, width=2, height=4, bg="white")
b47.grid(row=11, column=15, sticky="NS")
bSeguro5 = Button(miFrame, width=2, height=4, bg="blue", text="★", fg="white")
bSeguro5.grid(row=11, column=14, sticky="NS")
b45 = Button(miFrame, width=2, height=4, bg="white")
b45.grid(row=11, column=13, sticky="NS")
b44 = Button(miFrame, width=2, height=4, bg="white")
b44.grid(row=11, column=12, sticky="NS")
b43 = Button(miFrame, width=2, height=4, bg="white")
b43.grid(row=11, column=11, sticky="NS")

#----Escalera Verde-----
bSeguro6 = Button(miFrame, width=2, height=4, text="★", bg="green", fg="White")
bSeguro6.grid(row=10, column=18, sticky="NS")
bEscaVer1 = Button(miFrame, width=2, height=4, bg="green")
bEscaVer1.grid(row=10, column=17, sticky="NS")
bEscaVer2 = Button(miFrame, width=2, height=4, bg="green")
bEscaVer2.grid(row=10, column=16, sticky="NS")
bEscaVer3 = Button(miFrame, width=2, height=4, bg="green")
bEscaVer3.grid(row=10, column=15, sticky="NS")
bEscaVer4 = Button(miFrame, width=2, height=4, bg="green")
bEscaVer4.grid(row=10, column=14, sticky="NS")
bEscaVer5 = Button(miFrame, width=2, height=4, bg="green")
bEscaVer5.grid(row=10, column=13, sticky="NS")
bEscaVer6 = Button(miFrame, width=2, height=4, bg="green")
bEscaVer6.grid(row=10, column=12, sticky="NS")
bEscaVer7 = Button(miFrame, width=2, height=4, bg="green")
bEscaVer7.grid(row=10, column=11, sticky="NS")
#bMetaVerde = Button(miFrame, width=2, height=4, bg="#CCCCFF",)
#bMetaVerde.grid(row=10, column=10, sticky="NS")

#------------Tablero Inferior--------------
b33 = Button(miFrame, width=10, bg="white")
b33.grid(row=12, column=8, sticky="WENS")
b32 = Button(miFrame, width=10, bg="white")
b32.grid(row=13, column=8, sticky="WENS")
b31 = Button(miFrame, width=10, bg="white")
b31.grid(row=14, column=8, sticky="WENS")
b30 = Button(miFrame, width=10, bg="white")
b30.grid(row=15, column=8, sticky="WENS")
bSeguro3 = Button(miFrame, width=10, bg="#F7DE3A",  text="★", fg="white")
bSeguro3.grid(row=16, column=8, sticky="WENS")
b28 = Button(miFrame, width=10, bg="white")
b28.grid(row=17, column=8, sticky="WENS")
b27 = Button(miFrame, width=10, bg="white")
b27.grid(row=18, column=8, sticky="WENS")
b26 = Button(miFrame, width=10, bg="white")
b26.grid(row=19, column=8, sticky="WENS")

b35 = Button(miFrame, width=10, bg="white")
b35.grid(row=12, column=10, sticky="WENS")
b36 = Button(miFrame, width=10, bg="white")
b36.grid(row=13, column=10, sticky="WENS")
b37 = Button(miFrame, width=10, bg="white")
b37.grid(row=14, column=10, sticky="WENS")
b38 = Button(miFrame, width=10, bg="white")
b38.grid(row=15, column=10, sticky="WENS")
bSalidaAzul = Button(miFrame, width=10, bg="blue")
bSalidaAzul.grid(row=16, column=10, sticky="WENS")
b40 = Button(miFrame, width=10, bg="white")
b40.grid(row=17, column=10, sticky="WENS")
b41 = Button(miFrame, width=10, bg="white")
b41.grid(row=18, column=10, sticky="WENS")
b42 = Button(miFrame, width=10, bg="white")
b42.grid(row=19, column=10, sticky="WENS")

#----Escalera Azul-----
bSeguro4 = Button(miFrame, width=10, text="★", bg="blue", fg="White")
bSeguro4.grid(row=19, column=9, sticky="WENS")
bEscaAzul1 = Button(miFrame, width=10, bg="blue")
bEscaAzul1.grid(row=18, column=9, sticky="WENS")
bEscaAzul2 = Button(miFrame, width=10, bg="blue")
bEscaAzul2.grid(row=17, column=9, sticky="WENS")
bEscaAzul3 = Button(miFrame, width=10, bg="blue")
bEscaAzul3.grid(row=16, column=9, sticky="WENS")
bEscaAzul4 = Button(miFrame, width=10, bg="blue")
bEscaAzul4.grid(row=15, column=9, sticky="WENS")
bEscaAzul5 = Button(miFrame, width=10, bg="blue")
bEscaAzul5.grid(row=14, column=9, sticky="WENS")
bEscaAzul6 = Button(miFrame, width=10, bg="blue")
bEscaAzul6.grid(row=13, column=9, sticky="WENS")
bEscaAzul7 = Button(miFrame, width=10, bg="blue")
bEscaAzul7.grid(row=12, column=9, sticky="WENS")

raiz.mainloop()
